name: Build Test

on:
  workflow_dispatch:       # also allow manual runs

permissions:
  contents: write
  pull-requests: write

jobs:

  build:
    name: Build ${{ matrix.host }}
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
      matrix:
        host: [desktop, laptop, kodi, attic]
    steps:

      - uses: actions/checkout@v5

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Install attic client
        run: nix profile install nixpkgs#attic-client

      - name: Authenticate with attic
        env:
          ATTIC_AUTH_TOKEN: "${{ secrets.ATTIC_AUTH_TOKEN }}"
        run: attic login default https://attic.a5f.org "$ATTIC_AUTH_TOKEN"

      - name: Build and push toplevel
        run: |
          TOPLEVEL=$(nix build \
            .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel \
            --print-build-logs \
            --print-out-paths \
            --no-link)
          attic push default:system "$TOPLEVEL"